services:
  db:
    image: postgres:18 # Use the official Postgres image from Docker Hub
    restart: always
    shm_size: 128mb # Recommended for performance
    ports:
      - "5432:5432" # Map port 5432 on the host to port 5432 in the container
    environment:
      POSTGRES_USER: altanfiz # Sets the default user
      POSTGRES_PASSWORD: altanfizgenity # Sets the user password
      POSTGRES_DB: shopee-db # Sets the default database name
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
